### PR TITLE
show own grades

### PR DESCRIPTION
**Pull request by t0mbrn**
### Pull Request
Please fill out the following template when you create a PR. This will help to process your PR faster!

#### Description
I proprose the following changes in my PR:
- Ability to show your own grade in the grade summary
- Ability to toggle this behavior

Here you can also add screenshots, if applicable.
image
image
image

#### References
I created the PR because I felt like its a nice addition

Referenced Issue:

Referenced ToDo from [project-board](https://github.com/orgs/TUfast-TUD/projects/1):

#### Type of change
- [ ] Bug fix (non-breaking change which fixes a bug)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that might cause existing functionality to not work as expected)

#### Further info
- [ ] This change requires a documentation update
- [ ] I updated the documentation accordingly, if required
- [ ] I commented my code where its useful

#### Testing
We have 1500+ Users. Please test your changes thoroughly.
- [x] Tested my changes on Firefox
- [ ] Tested my changes on Chromium-Based-Browsers
- [x] Successfully run `npm run test` locally

#### Additional Information
Add anything here, that might be important.

### CODE REVIEW

**Comment by t0mbrn** [comment]
FYI the grey bar in the robolab one are place holders I added for whenever there is no parseable data behind the link

**Comment by A-K-O-R-A** [comment]
Looks good, like I said I'll look into it next week. Thank you for adding an option to toggle the highlighting of the own grade :)

Out of curiosity, what is the meaning of the WG in selmajExamThemeWG?

**Comment by t0mbrn** [comment]
> Looks good, like I said I'll look into it next week. Thank you for adding an option to toggle the highlighting of the own grade :)

No worries!

> Out of curiosity, what is the meaning of the WG in selmajExamThemeWG?

WithGrade

**Comment by t0mbrn** [comment]
As it takes sometimes like 1.5 secs to load I added a simple loading animation for the grade summary

https://github.com/user-attachments/assets/02840724-4f96-40ae-b084-1ebc1a323edf

**Comment by t0mbrn** [comment]
ill move the PR to the main repo

**Comment by A-K-O-R-A** [comment]
Okay I'll close this then, I'll also add some comments on your new pull request, thanks for the patience :)

**Pull request closed without merging**
